ribbon:
  eager-load:
    enabled: true

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**
  ribbon:
    eager-load:
      enabled: true
debug: true
trace: true
logging:
  level:
    org:
        springframework:
          cloud:
            netflix: trace
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
hystrix:
  command:
    vets-service:
      execution:
        timeout:
          enabled: false
hystrix:
  command:
    visits-service:
      execution:
        timeout:
          enabled: false
hystrix:
  command:
    customers-service:
      execution:
        timeout:
          enabled: false
hystrix:
  command:
    api-gateway:
      execution:
        timeout:
          enabled: false
vets-service:
    ReadTimeout: 150000
    ConnectTimeout: 150000
visits-service:
    ReadTimeout: 150000
    ConnectTimeout: 150000
customers-service:
    ReadTimeout: 150000
    ConnectTimeout: 150000
api-gateway:
    ReadTimeout: 150000
    ConnectTimeout: 150000

health:
  config:
    enabled: false
