ribbon:
  eager-load:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 10000

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**
  ribbonIsolationStrategy: THREAD
  ribbon:
    eager-load:
      enabled: true
debug: true
trace: true
logging:
  level:
    org:
        springframework:
          cloud:
            netflix: trace
hystrix:
  command:
    default:
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 45000
    vets-service:
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 45000
    visits-service:
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 45000
    customers-service:
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 45000
    api-gateway:
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 45000
vets-service:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000
visits-service:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000
customers-service:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000
api-gateway:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000

health:
  config:
    enabled: false
